# Generated by Django 3.2.25 on 2025-07-13 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('overall_total_games', models.IntegerField(default=0)),
                ('overall_wins', models.IntegerField(default=0)),
                ('overall_win_rate', models.FloatField(db_index=True, default=0.0)),
                ('overall_rank', models.IntegerField(blank=True, db_index=True, null=True)),
                ('overall_sundays_attended', models.IntegerField(default=0)),
                ('overall_guest_games_played', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
