# Generated by Django 3.2.25 on 2025-07-13 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_player'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('game_date', models.DateField(auto_now=True, db_index=True)),
                ('court', models.CharField(choices=[('a', 'A'), ('b', 'B')], default='a', max_length=1)),
                ('game_type', models.CharField(choices=[('singles', 'singles'), ('doubles', 'doubles')], default='doubles', max_length=10)),
                ('team1_is_winner', models.BooleanField()),
                ('team2_is_winner', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(db_index=True, default=0.0)),
                ('rank', models.IntegerField(blank=True, db_index=True, null=True)),
                ('sundays_attended', models.IntegerField(default=0)),
                ('guest_games_played', models.IntegerField(default=0)),
                ('odl_rank', models.IntegerField(blank=True, help_text='Special rank for a One Day League event.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-win_rate', '-wins'],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(choices=[('a', 'A'), ('b', 'B')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('game_type', models.CharField(choices=[('singles', 'singles'), ('doubles', 'doubles')], default='doubles', max_length=10)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('min_sundays_for_rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['start_date', 'end_date'], name='game_season_start_d_ab49bd_idx'),
        ),
        migrations.AddField(
            model_name='queue',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_as_player1', to='account.player'),
        ),
        migrations.AddField(
            model_name='queue',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_as_player2', to='account.player'),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='best_partner',
            field=models.ForeignKey(blank=True, help_text='The player with whom this player has the highest win rate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_partner_for', to='account.player'),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='account.player'),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='game.season'),
        ),
        migrations.AddField(
            model_name='game',
            name='player1_team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_as_player1_team1', to='account.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player1_team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_as_player1_team2', to='account.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_as_player2_team1', to='account.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_as_player2_team2', to='account.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.season'),
        ),
        migrations.AddField(
            model_name='game',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['court', 'game_type', 'created_at'], name='game_queue_court_d0189b_idx'),
        ),
        migrations.AddIndex(
            model_name='playerseasonstat',
            index=models.Index(fields=['player', 'season'], name='game_player_player__400e1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerseasonstat',
            unique_together={('player', 'season')},
        ),
    ]
